# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('muscle_group', models.CharField(choices=[('q', 'quads'), ('h', 'hamstrings'), ('c', 'calves'), ('a', 'abs'), ('p', 'pecs'), ('s', 'shoulders'), ('l', 'lats'), ('b', 'biceps'), ('t', 'triceps'), ('m', 'mobility')], max_length=1)),
                ('sets', models.CharField(max_length=10)),
                ('reps', models.CharField(max_length=10)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Account')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Workout'),
        ),
    ]
