# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20170410_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
